apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
