apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "security_level"
    operator: "Equal"
    value: "2"
    effect: "NoSchedule"
  - key: "security_level"
    operator: "Equal"
    value: "3"
    effect: "NoSchedule"
  - key: "security_level"
    operator: "Equal"
    value: "4"
    effect: "NoSchedule"
