apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:1.30
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    command:
    - /bin/sh
    - -c
    - |
      # Keep service alive
      while true
      do
        sleep infinity
      done
