apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: add-eu-region-node-affinity
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    labelSelector:
      matchLabels:
        data-sovereignty: eu
  location: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms
  parameters:
    operation: merge
    pathTests:
    - subPath: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms
      condition: MustNotExist
    values:
      fromList:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            # Azure regions
            - francecentral
            - francesouth
            - germanynorth
            - germanywestcentral
            - italynorth
            - northeurope
            - norwayeast
            - norwaywest
            - polandcentral
            - spaincentral
            - swedencentral
            - switzerlandnorth
            - switzerlandwest
            - westeurope
            # AWS regions
            - eu-central-1
            - eu-central-2
            - eu-north-1
            - eu-south-1
            - eu-south-2
            - eu-west-1
            - eu-west-3
            # GCP regions
            - europe-central2
            - europe-north1
            - europe-southwest1
            - europe-west1
            - europe-west3
            - europe-west4
            - europe-west6
            - europe-west8
            - europe-west9
            - europe-west12
---
apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: add-us-region-node-affinity
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    labelSelector:
      matchLabels:
        data-sovereignty: us
  location: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms
  parameters:
    operation: merge
    pathTests:
    - subPath: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms
      condition: MustNotExist
    values:
      fromList:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            # Azure regions
            - centralus
            - centraluseuap
            - centralusstage
            - eastus
            - eastus2
            - eastus2euap
            - eastus2stage
            - eastusstage
            - eastusstg
            - northcentralus
            - northcentralusstage
            - southcentralus
            - southcentralusstage
            - southcentralusstg
            - westcentralus
            - westus
            - westus2
            - westus2stage
            - westus3
            - westusstage
            # AWS regions
            - us-east-1
            - us-east-2
            - us-gov-east-1
            - us-gov-west-1
            - us-west-1
            - us-west-2
            # GCP regions
            - us-central1
            - us-east1
            - us-east4
            - us-east5
            - us-south1
            - us-west1
            - us-west2
            - us-west3
            - us-west4
